name = "SDA"
uuid = "7f8011be-c323-48c5-ba80-8fbbe90ab35e"
authors = ["WhiffleFish <tylertronics@gmail.com>"]
version = "0.1.0"

[deps]
CounterfactualRegret = "9fefe0b7-a0d5-4e12-a8ed-3472cccdfc49"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
